language: java

jdk:
  - oraclejdk8
  
script:
  - javac -classpath "libraries/jl1.0.1.jar" javazoom/jl/player/PausablePlayer.java
  - javac -classpath "libraries/dragshotMod.jar:libraries/easyogg/easyogg.jar:libraries/jl1.0.1.jar:libraries/easyogg/jogg-0.0.7.jar:libraries/easyogg/jorbis-0.0.15.jar:./" *.java -Xlint:deprecation
